import {
  AUTO_SCHEDULE_MESSAGE,
  CAMPAIGNS,
  COMPOSER_CANVA,
  CUSTOM_APPROVALS,
  DISABLE_HASHTAG_SUGGESTIONS,
  INSTAGRAM_STORIES,
  LINK_SETTINGS_ADVANCED,
  LINKEDIN_PDF_PUBLISHING,
  MESSAGE_TAGGING,
  PRODUCT_ACCESS_HASHTAG_SUGGESTIONS,
  RECOMMENDED_TIMES_TO_POST,
  SCHEDULE_MESSAGES,
  VIDEO_TRANSCODING,
} from 'fe-lib-entitlements'

export const FEATURE_CODES = [
  AUTO_SCHEDULE_MESSAGE,
  CAMPAIGNS,
  COMPOSER_CANVA,
  CUSTOM_APPROVALS,
  DISABLE_HASHTAG_SUGGESTIONS,
  INSTAGRAM_STORIES,
  LINK_SETTINGS_ADVANCED,
  LINKEDIN_PDF_PUBLISHING,
  MESSAGE_TAGGING,
  PRODUCT_ACCESS_HASHTAG_SUGGESTIONS,
  RECOMMENDED_TIMES_TO_POST,
  SCHEDULE_MESSAGES,
  VIDEO_TRANSCODING,
]

export const FEATURE_UNLIMITED = -1
