const SOURCE = {
  WEB: 'WEB',
  MOBILE: 'MOBILE',
  AMPLIFY: 'AMPLIFY',
}

export const MESSAGE_STATE = {
  SCHEDULED: 'SCHEDULED',
  SENT: 'SENT',
  SEND_FAILED_PERMANENTLY: 'SEND_FAILED_PERMANENTLY',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  EXPIRED_APPROVAL: 'EXPIRED_APPROVAL',
  REJECTED_APPROVAL: 'REJECTED_APPROVAL',
  PENDING_PRESCREEN: 'PENDING_PRESCREEN',
  REJECTED_PRESCREEN: 'REJECTED_PRESCREEN',
  TRANSCODING: 'TRANSCODING',
}

export default {
  SOURCE,
  STATE: MESSAGE_STATE,
}
