const STATE = {
  ACTIVE: 'ACTIVE',
  AD_CAMPAIGN: 'AD_CAMPAIGN',
  ARCHIVED: 'ARCHIVED',
  COMPLETED: 'COMPLETED',
  DELETED: 'DELETED',
  DRAFTS: 'DRAFTS',
  DRAFT: 'DRAFT',
  DISCONNECTED: 'DISCONNECTED',
  DISCONNECTED_NETWORK: 'DISCONNECTED_NETWORK',
  EXPIRED_APPROVAL: 'EXPIRED_APPROVAL',
  NATIVE: 'NATIVE',
  PASTDRAFT: 'PASTDRAFT',
  PAUSED: 'PAUSED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  PENDING_PRESCREEN: 'PENDING_PRESCREEN',
  REJECTED_APPROVAL: 'REJECTED_APPROVAL',
  REJECTED_PRESCREEN: 'REJECTED_PRESCREEN',
  SCHEDULED: 'SCHEDULED',
  SEND_FAILED_PERMANENTLY: 'SEND_FAILED_PERMANENTLY',
  SENT: 'SENT',
  SUSPENDED: 'SUSPENDED',
  TRANSCODING: 'TRANSCODING',
  WITH_ISSUES: 'WITH_ISSUES',
} as const;

const REVIEWER_TYPES = {
  ADMIN_AND_EDITOR: 'ADMIN_AND_EDITOR',
  MEMBER: 'MEMBER',
  SYSTEM: 'SYSTEM',
  TEAM: 'TEAM',
} as const;

const TYPE = {
  ADCAMPAIGN: 'ADCAMPAIGN',
  DRAFT: 'DRAFT',
  MESSAGE: 'MESSAGE',
} as const;

const REVIEWER_NAMES = {
  NEXGATE: 'Nexgate',
} as const;

const PUBLISHING_MODES = {
  DIRECT_PUBLISH: 'IG_API',
  PUSH_PUBLISH: 'IG_PUSH',
} as const;

const POST_TYPES = {
  FACEBOOKPAGE: 'FACEBOOKPAGE',
  INSTAGRAM: 'INSTAGRAM',
  INSTAGRAMBUSINESS: 'INSTAGRAMBUSINESS',
  LINKEDINCOMPANY: 'LINKEDINCOMPANY',
  LINKEDINPROFILE: 'LINKEDINPROFILE',
  TWITTER: 'TWITTER',
} as const;

const DRAFT_MESSAGE_TYPE = 'draft';

const INSTAGRAM_POST_TYPE = {
  IG_FEED: 'IG_FEED',
  IG_STORY: 'IG_STORY',
} as const;

export const ContentConstants = {
  REVIEWER_NAMES,
  REVIEWER_TYPES,
  STATE,
  TYPE,
  PUBLISHING_MODES,
  POST_TYPES,
  DRAFT_MESSAGE_TYPE,
  INSTAGRAM_POST_TYPE,
} as const;
